"use strict";
const assert=require('node:assert/strict'),P=require('../web/panel_explode.js'),B=require('../web/vendor/babylon.js');
const positions=Float32Array.from([0,1,0,2,1,0,0,-1,0,2,-1,0,1,0,0]);
const elements=new Map([[1,{nodes:[0,1],group:{kind:'quad'}}],[2,{nodes:[0,1],group:{kind:'bar'}}],[3,{nodes:[2,3],group:{kind:'quad'}}],[4,{nodes:[2,3],group:{kind:'bar'}}],[5,{nodes:[0,4],group:{kind:'bar'}}]]);
const panels=[{id:1,skin:'upper',shell_eids:[1],stringer_eids:[2]},{id:2,skin:'lower',shell_eids:[3],stringer_eids:[4]}],p=P.create(),original=Array.from(positions);p.configure({panels},elements,positions);
assert.equal(p.active,false);assert.deepEqual(p.offsetElement(1),[0,0,0]);p.restore({enabled:true,distance:2,origin:'centroid'});assert.equal(p.active,true);assert.deepEqual(p.center,[1,0,0]);assert.deepEqual(p.offsetElement(1),[0,2,0]);assert.deepEqual(p.offsetElement(2),p.offsetElement(1));assert.deepEqual(p.offsetElement(3),[0,-2,0]);assert.deepEqual(p.offsetElement(5),[0,0,0]);assert.deepEqual(p.point(1,[1,1,0]),[1,3,0]);assert.deepEqual(Array.from(positions),original);
p.restore({enabled:true,distance:.6,origin:'midspan'});assert.deepEqual(p.center,[1,0,0]);assert.equal(Math.hypot(...p.offsetElement(1)),.6);
const engine=new B.NullEngine(),scene=new B.Scene(engine),mesh=new B.Mesh('panel',scene);mesh.metadata={feGroup:{panel_id:1}};p.applyMesh(mesh);assert.deepEqual(mesh.position.asArray(),[0,.6,0]);p.restore({...p.capture(),enabled:false});p.applyMesh(mesh);assert.deepEqual(mesh.position.asArray(),[0,0,0]);
for(const value of [{distance:-1},{distance:NaN},{distance:10001},{enabled:'yes'},{origin:'bad'},[]])assert.throws(()=>p.restore(value));assert.equal(p.active,false);
const bayPositions=Float32Array.from([0,1,1,2,1,2,0,-1,1,2,-1,2,3,2,2.2,4,2,2.8,3,0,2.2,4,0,2.8]);
const bayElements=new Map(),bayPanels=[];
for(let k=0;k<4;k++){bayElements.set(10+2*k,{nodes:[2*k,2*k+1],group:{kind:'quad'}});bayElements.set(11+2*k,{nodes:[2*k,2*k+1],group:{kind:'bar'}});bayPanels.push({id:k+1,skin:k%2?'lower':'upper',rib_bay:Math.floor(k/2)+1,start_rib:k>1?null:1,end_rib:k>1?null:2,key:(k%2?'lower':'upper')+':bay'+(Math.floor(k/2)+1)+':stringer1:segment1',shell_eids:[10+2*k],stringer_eids:[11+2*k]});}
const ribLayout={ribs:[{number:1,front:[0,0,0],rear:[2,0,0]},{number:2,front:[1,2,0],rear:[3,2,0]},{number:3,front:[2,5,2],rear:[4,5,2]}]};
p.configure({panels:bayPanels},bayElements,bayPositions,ribLayout);p.restore({enabled:true,origin:'ribbay',distance:.8});
for(const panel of bayPanels){const expected=panel.rib_bay===1?[1,0,1.5]:[3.5,1,2.5];assert.deepEqual(p.originPanel(panel.id),expected);const offset=p.offsetPanel(panel.id);assert(Math.abs(offset[0])<1e-7&&Math.abs(offset[2])<1e-7);assert(Math.abs(offset[1]-(panel.skin==='upper'?.8:-.8))<1e-7);assert.deepEqual(p.offsetElement(panel.stringer_eids[0]),offset);}
assert.deepEqual(p.capture(),{enabled:true,origin:'ribbay',distance:.8});const saved=p.capture();p.restore({...saved,enabled:false});assert.deepEqual(p.offsetPanel(3),[0,0,0]);p.restore(saved);
const mirrored=bayPositions.map((v,k)=>k%3===0?-v:v),mirroredRibs={ribs:ribLayout.ribs.map(r=>({...r,front:r.front.map((v,k)=>k===1?-v:v),rear:r.rear.map((v,k)=>k===1?-v:v)}))};p.configure({panels:bayPanels},bayElements,mirrored,mirroredRibs);assert.deepEqual(p.originPanel(3),[-3.5,1,2.5]);assert(Math.abs(p.offsetPanel(3)[1]-.8)<1e-7);
p.configure({panels:bayPanels},bayElements,bayPositions);assert(Math.abs(p.originPanel(3)[0]-3.5)<1e-7);assert(Math.abs(p.originPanel(3)[1]-1)<1e-7);assert(Math.abs(p.originPanel(3)[2]-2.5)<1e-7);
p.restore({enabled:true,origin:'ribbay',distance:0});assert.deepEqual(p.offsetPanel(3),[0,0,0]);assert.equal(p.active,false);p.configure({panels:[]},new Map(),null);assert.deepEqual(p.center,[0,0,0]);scene.dispose();engine.dispose();console.log('Panel explosion: global/per-bay origins, runouts, mirrored coordinates, rigid offsets, zero distance and persistence passed.');
