"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),B=require("../web/vendor/babylon.js"),L=require("../web/scene_lighting.js"),checks=[];
const defaults=L.normalize();assert.deepEqual(defaults,{preset:"balanced",ambient:.3,key:.3,fill:.2,headlight:.48,keyDirection:[-.5,-.7,-1],fillDirection:[.6,.35,.8]});
for(const bad of[{ambient:-1},{key:NaN},{fill:4},{keyDirection:[0,0,0]},{fillDirection:[1,2]},{keyDirection:[1,Infinity,0]},{preset:"bad"},[]])assert.throws(()=>L.normalize(bad));assert.equal(L.normalize({key:0}).key,0);const copy=L.normalize();copy.keyDirection[0]=99;assert.equal(L.normalize().keyDirection[0],-.5);checks.push("Directional balanced studio defaults avoid clipped light sums; invalid intensities/directions are rejected and returned settings do not alias defaults");
for(const [preset,intensities]of Object.entries({balanced:[.92,.82,.56],soft:[1.05,.5,.42],technical:[.78,1,.7]})){const original={...L.normalize({preset}),ambient:intensities[0],key:intensities[1],fill:intensities[2]};assert.deepEqual(L.normalize(original),L.normalize({preset}));assert.deepEqual(L.normalize({...original,preset:"custom"}),{...original,preset:"custom"});assert.deepEqual(L.normalize({...original,key:1.234}),{...original,key:1.234});const edited={...original,keyDirection:[1,2,3]};assert.deepEqual(L.normalize(edited),edited);}checks.push("Exact historical named presets upgrade on Study load, while custom settings and edited preset intensities/directions remain unchanged");
for(const [preset,intensities]of Object.entries({balanced:[.32,.8,.24,.35],soft:[.44,.58,.28,.3],technical:[.23,.88,.18,.28]})){const old={...L.normalize({preset}),ambient:intensities[0],key:intensities[1],fill:intensities[2],headlight:intensities[3]};assert.deepEqual(L.normalize(old),L.normalize({preset}));assert.deepEqual(L.normalize({...old,preset:'custom'}),{...old,preset:'custom'});assert.deepEqual(L.normalize({...old,headlight:.91}),{...old,headlight:.91});delete old.headlight;assert.deepEqual(L.normalize(old),L.normalize({preset}));}checks.push('Previous untouched named presets receive balanced all-angle illumination; explicit camera edits and custom settings are preserved');
const engine=new B.NullEngine(),scene=new B.Scene(engine),foreign=new B.HemisphericLight("foreign",new B.Vector3(0,1,0),scene),events=[],helper=L.create({BABYLON:B,scene,onChange:value=>events.push(value)});
assert.equal(scene.lights.length,5);assert.equal(scene.textures.length,0);assert.deepEqual(helper.capture(),defaults);
assert.deepEqual(helper.lights[0].groundColor.asArray(),[.72,.72,.72]);assert.deepEqual(helper.lights[1].diffuse.asArray(),[1,1,1]);assert.deepEqual(helper.lights[2].diffuse.asArray(),[1,1,1]);
for(const[index,field]of[[1,"keyDirection"],[2,"fillDirection"]]){const fe=defaults[field],length=Math.hypot(...fe),actual=helper.lights[index].direction.asArray();assert(actual.every((x,i)=>Math.abs(x-[fe[1],fe[2],fe[0]][i]/length)<1e-12));}
checks.push("Exactly four scene-owned lights map saved FE directions into viewport YZX and allocate no textures or reflection cubes");
const custom={preset:"custom",ambient:0,key:1.6,fill:.9,headlight:.4,keyDirection:[1,2,3],fillDirection:[-3,-2,-1]};helper.restore(custom);assert.equal(events.length,0);assert.deepEqual(helper.capture(),custom);helper.apply({...custom,key:1.7},{notify:true});assert.equal(events.length,1);events[0].keyDirection[0]=999;assert.equal(helper.capture().keyDirection[0],1);const before=helper.capture();assert.throws(()=>helper.apply({keyDirection:[0,0,0]}));assert.deepEqual(helper.capture(),before);helper.reset();assert.deepEqual(helper.capture(),defaults);checks.push("Restoration is silent, UI notification snapshots are independent, invalid edits leave the applied lights unchanged, and reset restores defaults");
const camera=new B.FreeCamera("view",new B.Vector3(3,-4,6),scene);scene.activeCamera=camera;camera.setTarget(B.Vector3.Zero());scene.render();assert(helper.lights[3].direction.equalsWithEpsilon(camera.getForwardRay().direction,1e-12));camera.position.set(-3,4,-6);camera.setTarget(B.Vector3.Zero());scene.render();assert(helper.lights[3].direction.equalsWithEpsilon(camera.getForwardRay().direction,1e-12));assert.equal(L.normalize({preset:"custom"}).headlight,0);assert.throws(()=>L.normalize({headlight:4}));checks.push("Camera fill follows top/underside camera direction, explicit zero disables it and legacy custom lighting is preserved without adding a fill");
for(let i=0;i<20;i++)helper.restore({preset:i%2?"soft":"technical"});assert.equal(scene.lights.length,5);helper.dispose();helper.dispose();assert.equal(scene.lights.length,1);assert.strictEqual(scene.lights[0],foreign);assert.throws(()=>helper.apply(),/disposed/);const another=L.create({BABYLON:B,scene});scene.dispose();assert.throws(()=>another.apply(),/disposed/);engine.dispose();checks.push("Repeated presets allocate no extra lights; explicit disposal preserves unrelated lights and scene disposal owns automatic cleanup");
if(process.argv[2]){const out=path.resolve(process.argv[2]);fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,"lighting-unit-summary.json"),JSON.stringify({passed:true,groups:checks.length,checks},null,2));}console.log(`Scene lighting passed ${checks.length} groups.`);
