(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.WingImportedAnalysis=api;})(globalThis,function(){
 'use strict';
 const DEFAULTS={solution:'source',follower:'source',modes:10,buckling_max_factor:100,load_steps:20,max_iterations:40,max_cutbacks:12,displacement_tolerance:1e-6,residual_tolerance:1e-5};
 function options(raw){
  if(raw!=null&&(typeof raw!=='object'||Array.isArray(raw)))throw Error('Invalid imported analysis settings.');
  const value={...DEFAULTS,...raw};value.solution=String(value.solution);value.follower=String(value.follower);
  if(!['source','101','103','105','106'].includes(value.solution)||!['source','fixed','force'].includes(value.follower))throw Error('Unsupported imported analysis settings.');
  for(const key of Object.keys(DEFAULTS).filter(k=>typeof DEFAULTS[k]==='number'))if(!Number.isFinite(value[key])||value[key]<0)throw Error('Invalid '+key+' setting.');
  return value.solution==='source'&&value.follower==='source'?{...DEFAULTS}:Object.fromEntries(Object.keys(DEFAULTS).map(key=>[key,value[key]]));
 }
 function signature(deck){const value=options(deck?.source?.analysis);return value.solution==='source'&&value.follower==='source'?deck.signature:deck.signature+'|'+JSON.stringify(value);}
 function solution(deck){const value=options(deck?.source?.analysis);return value.solution==='source'?String(deck.solution):value.solution;}
 function matches(raw,deck){return JSON.stringify(options(raw))===JSON.stringify(options(deck?.source?.analysis));}
 function cases(deck){return (deck.cases||[]).filter(row=>options(deck.source?.analysis).solution==='source'?row.result_required!==false:row.case_control?.STATSUB==null&&!String(row.analysis_role||'').startsWith('Buckling'));}
 function create({host,read,onChange}){
  host.innerHTML='<h2>Imported deck analysis</h2><label class="display-control">Solution <select data-key="solution"><option value="source">Original source solution</option><option value="101">SOL101 · linear static</option><option value="103">SOL103 · normal modes</option><option value="105">SOL105 · linear buckling</option><option value="106">SOL106 · nonlinear static</option></select></label><label class="display-control">Concentrated FORCE loads <select data-key="follower"><option value="source">Keep source follower settings</option><option value="fixed">Fixed directions</option><option value="force">Follower forces · FORCE ROT</option></select></label><p class="pick-note">Original geometry, properties, LOAD sets, SPCs and MPCs are preserved. The selected solution is written to a separate run deck. SOL105 creates a buckling companion for each original static case. Imported SOL106 runs that solution only. Save Study includes these settings; the original BDF text stays unchanged.</p><p class="pick-note">Follower mode rotates concentrated FORCE directions with nodal rotations: SOL101 uses the first-order load tangent; SOL106 updates directions during each iteration. MOMENT, pressure and body loads stay fixed. Follower forces are unavailable for SOL103/SOL105. Imported sensitivity currently supports SOL101 static adjoints only.</p><div data-eigen></div><div data-nonlinear></div><p data-note role="status"></p>';
  function numeric(parent,key,label,step){const line=document.createElement('label');line.className='display-control';line.textContent=label+' ';const input=document.createElement('input');input.type='number';input.dataset.key=key;input.step=String(step);input.min=key==='max_cutbacks'?'0':'0.00000000000001';line.append(input);parent.append(line);}
  for(const [key,label,step]of [['modes','Requested modes',1],['buckling_max_factor','Maximum buckling factor',1]])numeric(host.querySelector('[data-eigen]'),key,label,step);
  for(const [key,label,step]of [['load_steps','Initial load steps',1],['max_iterations','Iterations per step',1],['max_cutbacks','Maximum cutbacks',1],['displacement_tolerance','Displacement tolerance','any'],['residual_tolerance','Residual tolerance','any']])numeric(host.querySelector('[data-nonlinear]'),key,label,step);
  host.addEventListener('change',event=>{if(!event.target.dataset.key)return;try{const values=Object.fromEntries([...host.querySelectorAll('[data-key]')].map(el=>[el.dataset.key,el.type==='number'?Number(el.value):el.value]));onChange(options(values));refresh();}catch(error){host.querySelector('[data-note]').textContent=error.message;}});
  function refresh(disabled=false){const deck=read();host.hidden=!deck;if(!deck)return;const value=options(deck.source?.analysis),sol=solution(deck);for(const input of host.querySelectorAll('[data-key]')){input.value=value[input.dataset.key];input.disabled=disabled;}host.querySelector('[data-eigen]').hidden=!['103','105'].includes(value.solution);host.querySelector('[data-nonlinear]').hidden=value.solution!=='106';host.querySelector('[data-note]').textContent=value.follower==='force'&&!['101','106'].includes(sol)?'Select fixed forces for SOL103/SOL105 before running.':'Run SOL'+sol+' on '+deck.name+'; no wing geometry will be generated.';}
  return {refresh};
 }
 return {options,signature,solution,matches,cases,create};
});
