/* Physical leading-edge bay exclusions. Shell subdivisions never renumber bays. */
(function(root,factory){const api=factory(typeof module==="object"&&module.exports?require("./rib_layout.js"):root.WingRibLayout);if(typeof module==="object"&&module.exports)module.exports=api;else root.WingLeadingEdgeGaps=api;})(typeof globalThis!=="undefined"?globalThis:this,function(Ribs){
 "use strict";
 const KEY="leading_edge.disabled_bays",PARAM_KEYS=[...new Set([KEY,"leading_edge.enabled","leading_edge.start_rib","leading_edge.end_rib","planform.area","planform.aspect_ratio","planform.dihedral","box.end_eta","box.rib_pitch",...(Ribs?.PARAM_KEYS||[])])],views=new WeakMap();
 function parse(raw){
  if(typeof raw!=="string")throw new Error("Excluded bays must be a comma-separated list, for example 2,4-6.");
  const text=raw.trim();if(text.length>100000)throw new Error("The excluded-bay list is too long.");if(!text)return[];
  const values=new Set();let expanded=0;for(const token of text.split(",")){const m=/^\s*(\d+)\s*(?:-\s*(\d+)\s*)?$/.exec(token);if(!m)throw new Error("Use positive bay numbers or ascending ranges, for example 2,4-6.");const a=Number(m[1]),b=m[2]===undefined?a:Number(m[2]);if(!Number.isSafeInteger(a)||!Number.isSafeInteger(b)||a<1||b<a)throw new Error("Bay numbers must be positive integers; ranges must run from smaller to larger.");expanded+=b-a+1;if(expanded>10000)throw new Error("A bay range cannot contain more than 10,000 bays.");for(let bay=a;bay<=b;bay++){values.add(bay);if(values.size>10000)throw new Error("No more than 10,000 excluded bays can be defined.");}}
  return[...values].sort((a,b)=>a-b);
 }
 const roundEven=value=>{const n=Math.floor(value),f=value-n;return f===.5?(n%2===0?n:n+1):Math.round(value);};
 function derive(params){
  let disabled;try{disabled=parse(params[KEY]===undefined?"":params[KEY]);}catch(e){return{valid:false,error:e.message};}
  const area=params["planform.area"],ar=params["planform.aspect_ratio"],dihedral=params["planform.dihedral"],endEta=params["box.end_eta"],pitch=params["box.rib_pitch"];
  if(![area,ar,dihedral,endEta,pitch].every(v=>typeof v==="number"&&Number.isFinite(v))||area<=0||ar<=0||pitch<=0||endEta<=0||endEta>1||Math.abs(dihedral)>=89)return{valid:false,error:"Set valid area, aspect ratio, dihedral, box End ETA and rib pitch to number the bays."};
  const layout=Ribs?.physical(params);if(layout&&!layout.valid)return{valid:false,error:layout.error};
  const length=Math.sqrt(area*ar)/2*Math.sqrt(1+Math.tan(dihedral*Math.PI/180)**2)*endEta,bayCount=layout?layout.bayCount:Math.max(1,roundEven(length/pitch));
  if(!Number.isSafeInteger(bayCount))return{valid:false,error:"The physical bay count is too large to represent."};
  const enabled=params["leading_edge.enabled"]===true,start=params["leading_edge.start_rib"],requestedEnd=params["leading_edge.end_rib"],end=requestedEnd===0?bayCount+1:requestedEnd;
  if(!Number.isInteger(start)||start<1||!Number.isInteger(requestedEnd)||requestedEnd<0)return{valid:false,error:"First and last leading-edge ribs must be valid integers (last rib 0 follows the box end)."};
  if(enabled&&(start>=end||end>bayCount+1))return{valid:false,error:`Choose leading-edge ribs within 1–${bayCount+1}, with the last rib after the first.`};
  if(enabled&&disabled.some(b=>b>bayCount))return{valid:false,error:`Excluded bay numbers cannot exceed ${bayCount}, the final physical bay. Update the list or turn leading-edge meshing off.`};
  const activeStart=Math.max(1,Math.min(bayCount+1,start)),activeEnd=Math.max(activeStart,Math.min(bayCount+1,end)),excluded=disabled.filter(b=>b>=activeStart&&b<activeEnd),activeCount=enabled?activeEnd-activeStart-excluded.length:0;
  return{valid:true,disabled,bayCount,ribCount:bayCount+1,start:activeStart,end:activeEnd,requestedStart:start,requestedEnd:end,enabled,excluded,activeCount,ignored:disabled.filter(b=>b<activeStart||b>=activeEnd),layout};
 }
 function install(host,options){
  const doc=host.ownerDocument,input=doc.getElementById("p-"+KEY);if(!input)return null;
  let view=views.get(doc);if(!view){view={editor:null};for(const event of ["input","change"])doc.addEventListener(event,e=>{if(PARAM_KEYS.some(k=>e.target?.id==="p-"+k))view.editor?.refresh();});views.set(doc,view);}
  view.editor?.destroy?.();const section=doc.createElement("section");section.className="leading-edge-gaps";section.setAttribute("aria-label","Leading-edge gaps for pylons");
  section.innerHTML='<h3>Pylon / leading-edge gaps</h3><p>A checked bay is a gap: its leading-edge skins are omitted. Bay <b>b</b> lies between physical ribs <b>b</b> and <b>b + 1</b>. Use the excluded-bay field for numbers or ranges, for example <b>2,4-6</b>; leave it blank for no gaps.</p><div class="le-gap-actions"><button type="button" data-action="exclude">Exclude selected range</button><button type="button" data-action="restore">Restore selected range</button></div><p class="le-gap-status" role="status"></p><p class="le-gap-error" role="alert" hidden></p><div class="le-gap-bays" role="group" aria-label="Excluded physical leading-edge bays"></div><p class="le-gap-note"></p>';
  const row=input.closest(".row")||input.parentElement;row.insertAdjacentElement("afterend",section);input.placeholder="e.g. 2,4-6; blank = no gaps";input.setAttribute("aria-describedby","leading-edge-gap-status");section.querySelector(".le-gap-status").id="leading-edge-gap-status";
  const status=section.querySelector(".le-gap-status"),error=section.querySelector(".le-gap-error"),bays=section.querySelector(".le-gap-bays"),note=section.querySelector(".le-gap-note"),locked=()=>!!options.isLocked?.();let destroyed=false;
  function refresh(){if(destroyed)return;const data=derive(options.readValues());error.hidden=data.valid;error.textContent=data.valid?"":data.error;bays.replaceChildren();for(const button of section.querySelectorAll("button"))button.disabled=locked()||!data.valid;if(!data.valid){status.textContent="Correct the definition to show the physical bays.";note.textContent="";return;}
   const disabled=new Set(data.disabled);status.textContent=`${data.bayCount} physical bays · ${data.ribCount} ribs. ${data.enabled?`${data.activeCount} leading-edge bays active in ribs ${data.start}–${data.end}.`:"Leading-edge meshing is off; exclusions are retained."}${locked()?" Mesh parameters are locked.":""}`;
   const limit=Math.min(data.bayCount,200);for(let bay=1;bay<=limit;bay++){const label=doc.createElement("label"),checkbox=doc.createElement("input"),span=doc.createElement("span");checkbox.type="checkbox";checkbox.checked=disabled.has(bay);checkbox.disabled=locked();checkbox.dataset.bay=String(bay);checkbox.setAttribute("aria-label",`Exclude bay ${bay}, between ribs ${bay} and ${bay+1}`);span.textContent=String(bay);label.className="le-gap-bay";if(bay<data.start||bay>=data.end)label.classList.add("outside-range");label.title=`Bay ${bay}: ribs ${bay}–${bay+1}`+(bay<data.start||bay>=data.end?"; outside selected range, exclusion retained for later":"");label.append(checkbox,span);bays.appendChild(label);checkbox.onchange=()=>{if(locked()){refresh();return;}const values=new Set(parse(input.value));checkbox.checked?values.add(bay):values.delete(bay);commit(values,bay);};}
   note.textContent=(data.ignored.length?`${data.ignored.length} exclusion(s) outside the selected rib range are retained and ignored. `:"")+(data.bayCount>200?"The first 200 bays are shown; use the text field for higher numbers. ":"")+"Excluding every selected bay is allowed. End ribs close each remaining leading-edge section; no leading-edge elements are created when none remain.";
  }
  function commit(values,focusBay=null){input.value=[...values].sort((a,b)=>a-b).join(",");refresh();options.onEdit?.(KEY);if(focusBay!==null)bays.querySelector(`[data-bay="${focusBay}"]`)?.focus();}
  for(const button of section.querySelectorAll("button"))button.onclick=()=>{if(locked())return;const data=derive(options.readValues());if(!data.valid)return;const values=new Set(data.disabled);if(button.dataset.action==="exclude"&&data.end-data.start>10000){error.hidden=false;error.textContent="Use a smaller rib range; at most 10,000 excluded bays can be stored.";return;}if(button.dataset.action==="exclude"){for(let bay=data.start;bay<data.end;bay++)values.add(bay);}else for(const bay of values)if(bay>=data.start&&bay<data.end)values.delete(bay);if(values.size>10000){error.hidden=false;error.textContent="No more than 10,000 excluded bays can be stored.";return;}commit(values);};
  const lockChanged=()=>refresh();host.addEventListener("parameterlockchange",lockChanged);const editor={refresh,assertValidDraft(){const data=derive(options.readValues());if(!data.valid){refresh();throw new Error("Leading-edge gaps: "+data.error);}return data;},destroy(){destroyed=true;host.removeEventListener("parameterlockchange",lockChanged);}};view.editor=editor;refresh();return editor;
 }
 return{KEY,PARAM_KEYS,parse,roundEven,derive,install};
});
