/* Editable isotropic library and shell/beam assignments. Canonical data uses SI;
 * invalid input stays in the editor and dirty signature, never in the deck. */
(function(root){
 "use strict";
 const SHELLS=[["upper_skin","Upper skin","group-shell-properties","properties.t_skin_upper"],["lower_skin","Lower skin","group-shell-properties","properties.t_skin_lower"],["spar_web","Spar webs","group-spar-properties","properties.t_spar_web"],["rib_web","Rib webs","group-rib-properties","properties.t_rib_web"],["leading_edge_skin","Leading-edge skin","group-leading-edge-properties","leading_edge.t_skin"],["leading_edge_rib","Leading-edge ribs","group-leading-edge-properties","leading_edge.t_rib"]];
 const BARS=[["stringer","Stringers","group-beam-sections"],["spar_cap","Spar caps","group-spar-properties"],["rib_stiffener","Rib stiffeners","group-rib-properties"],["runout","Runout connectors","group-beam-sections"]];
 const KEYS=["materials.library","materials.shells","materials.bars"],SHARED_NOTE="Foam and honeycomb are editable effective isotropic elastic placeholders. Directional core behavior, crushing, damage and material failure are not modeled.";
 function install({document:doc=root.document,onEdit=()=>{}}={}){
  const canonical=Object.fromEntries(KEYS.map(key=>[key,doc.getElementById("p-"+key)]));if(KEYS.some(key=>!canonical[key]))return null;
  const nodes=[],cards=[],library=[],listeners=[],selects=[],hidden=[];let destroyed=false,updating=false;
  const el=(tag,text,cls)=>{const node=doc.createElement(tag);if(text!==undefined)node.textContent=text;if(cls)node.className=cls;return node;};
  const listen=(node,event,fn)=>{node.addEventListener(event,fn);listeners.push(()=>node.removeEventListener(event,fn));};
  const parse=key=>{const rows=JSON.parse(canonical[key].value||"[]");if(!Array.isArray(rows))throw Error(key+" needs an array.");return rows;};
  const parsed=Object.fromEntries(KEYS.map(key=>[key,parse(key)]));
  for(const key of KEYS){const row=canonical[key].closest(".row");if(row){hidden.push([row,row.hidden]);row.hidden=true;}}
  function input(parent,label,value,{scale=1,integer=false}={}){const row=el("label",label,"material-field"),control=el("input");control.type="text";control.inputMode=integer?"numeric":"decimal";control.value=value==null?"":String(Number((value*scale).toPrecision(15)));control.setAttribute("aria-label",label);row.append(control);parent.append(row);return control;}
  function numeric(control,scale=1){const raw=control.value.trim(),value=Number(raw);return raw!==""&&Number.isFinite(value)?Number((value*scale).toPrecision(15)):{raw:control.value};}
  function textInput(parent,label,value){const row=el("label",label,"material-field"),control=el("input");control.type="text";control.value=value??"";control.setAttribute("aria-label",label);row.append(control);parent.append(row);return control;}
  function selection(parent,label,choices,value){const row=el("label",label,"material-field"),control=el("select");control.setAttribute("aria-label",label);for(const[v,name]of choices){const option=el("option",name);option.value=String(v);control.append(option);}control.value=String(value);row.append(control);parent.append(row);return control;}
  function materialSelect(parent,label,value){const control=selection(parent,label,[],value);control.dataset.materialValue=String(value);selects.push(control);return control;}
  const host=doc.getElementById("group-materials")||canonical[KEYS[0]].parentElement,libraryRoot=el("section",undefined,"materials-library"),head=el("div",undefined,"materials-editor-heading"),heading=el("h3","Material library"),add=el("button","+ Add material");add.type="button";head.append(heading,add);libraryRoot.append(head,el("p","Material 1 uses the name and properties above. Additional materials below use GPa and kg/m³; calculations and saved files use Pa.","material-note"));const libraryBody=el("div",undefined,"materials-library-rows"),status=el("p",undefined,"material-error");status.setAttribute("role","alert");status.hidden=true;libraryRoot.append(libraryBody,status,el("p",SHARED_NOTE,"material-note"));host.append(libraryRoot);nodes.push(libraryRoot);
  function rawLibrary(){return library.map(row=>({id:row.id,name:row.name.value,E:numeric(row.E,1e9),nu:numeric(row.nu),rho:numeric(row.rho)}));}
  function rawCard(card){const row={component:card.component,material:Number(card.material.dataset.materialValue)};if(card.shell){row.kind=card.kind.value;row.face_material=Number(card.faceMaterial.dataset.materialValue);row.core_material=Number(card.coreMaterial.dataset.materialValue);row.face_thickness=numeric(card.face,1e-3);row.core_thickness=numeric(card.core,1e-3);}return row;}
  function raw(){return{"materials.library":rawLibrary(),"materials.shells":cards.filter(card=>card.shell&&card.present).map(rawCard),"materials.bars":cards.filter(card=>!card.shell&&card.present).map(rawCard)};}
  function validPositive(value,label){if(typeof value!=="number"||!Number.isFinite(value)||value<=0)throw Error(label+" must be a finite positive number.");}
  function validId(value,label){if(!Number.isInteger(value)||value<1||value>99999999)throw Error(label+" must select a valid material ID.");}
  function validate(){const draft=raw(),ids=new Set([1]);if(library.length>256)throw Error("The library supports at most 256 additional materials.");for(const row of draft[KEYS[0]]){validId(row.id,"Material");if(row.id===1||ids.has(row.id))throw Error("Additional material IDs must be unique and start at 2.");ids.add(row.id);row.name=row.name.trim();if(!row.name||/[\u0000-\u001f\u007f]/.test(row.name))throw Error("Material "+row.id+" needs a single-line name.");validPositive(row.E,"Material "+row.id+" E (GPa)");validPositive(row.rho,"Material "+row.id+" density");if(typeof row.nu!=="number"||!Number.isFinite(row.nu)||row.nu<0||row.nu>=.5)throw Error("Material "+row.id+" Poisson ratio must satisfy 0 <= nu < 0.5. Negative (auxetic) values are not supported by the native MAT1 path.");}
   for(const card of cards){const row=rawCard(card),prefix=card.label+": ";for(const key of card.shell?["material","face_material","core_material"]:["material"])validId(row[key],prefix+key);if(card.shell){if(!["monolithic","sandwich"].includes(row.kind))throw Error(prefix+"choose monolithic or sandwich construction.");validPositive(row.face_thickness,prefix+"each face thickness");validPositive(row.core_thickness,prefix+"core thickness");}
    for(const field of card.shell&&row.kind==="sandwich"?["face_material","core_material"]:["material"])if(!ids.has(row[field]))throw Error(prefix+"select a defined material (missing ID "+row[field]+").");
    if(card.shell&&row.kind==="sandwich"&&["rib_web","spar_web"].includes(card.component)){const key=card.component==="rib_web"?"properties.ribs":"properties.spar_bays",value=doc.getElementById("p-"+key)?.value;for(const override of JSON.parse(value||"[]"))for(const field of card.component==="rib_web"?["thickness"]:["front_thickness","rear_thickness"])if(override[field]!==undefined&&!(override[field]>2*row.face_thickness))throw Error(prefix+"the total thickness override for "+(card.component==="rib_web"?"rib "+override.rib:"bay "+override.bay)+" must exceed twice the face thickness; the remaining core must be positive.");}
   }
   draft[KEYS[0]].sort((a,b)=>a.id-b.id);return draft;
  }
  function materialOptions(){return[{id:1,name:doc.getElementById("p-material.name")?.value?.trim()||"Material 1"},...rawLibrary().map(row=>({id:row.id,name:row.name.trim()||"Unnamed material"}))];}
  function refreshSelects(){const options=materialOptions();for(const select of selects){const value=select.dataset.materialValue;select.replaceChildren();for(const row of options){const option=el("option",row.id+" · "+row.name);option.value=String(row.id);select.append(option);}if(!options.some(row=>String(row.id)===value)){const option=el("option","Missing material "+value);option.value=value;select.append(option);}select.value=value;}}
  const format=number=>Number.isFinite(number)?String(Number(Math.abs(number)>=100?number.toFixed(2):number.toPrecision(6))):"—";
  function draw(card){if(!card.shell)return;const row=rawCard(card),sandwich=row.kind==="sandwich";card.mono.hidden=sandwich;card.layers.hidden=!sandwich;if(card.thicknessRow)card.thicknessRow.hidden=sandwich||card.thicknessWasHidden;const face=row.face_thickness,core=row.core_thickness,total=sandwich?2*face+core:Number(doc.getElementById("p-"+card.thicknessKey)?.value);card.total.textContent="Total thickness: "+format(total*1000)+" mm";card.preview.replaceChildren();if(!Number.isFinite(total)||total<=0){card.viewport?.refresh();return;}const names=new Map(materialOptions().map(row=>[row.id,row.name])),parts=sandwich?[[face,"Face · "+names.get(row.face_material),"#74b9ed"],[core,"Core · "+names.get(row.core_material),"#bca575"],[face,"Face · "+names.get(row.face_material),"#74b9ed"]]:[[total,names.get(row.material)||"Missing material","#74b9ed"]];let y=15;for(let i=0;i<parts.length;i++){const[thickness,name,color]=parts[i],height=90*thickness/total,rect=doc.createElementNS("http://www.w3.org/2000/svg","rect");for(const[k,v]of Object.entries({x:12,y,width:108,height,fill:color,stroke:"#10283e","stroke-width":.7}))rect.setAttribute(k,String(v));card.preview.append(rect);const label=doc.createElementNS("http://www.w3.org/2000/svg","text");label.setAttribute("x","134");label.setAttribute("y",String(sandwich?28+i*35:62));label.setAttribute("fill","currentColor");label.setAttribute("font-size","11");label.textContent=name+" · "+format(thickness*1000)+" mm";card.preview.append(label);y+=height;}card.preview.setAttribute("aria-label",card.label+" "+row.kind+", total thickness "+format(total*1000)+" millimetres");card.sample.textContent="Section sample width: "+format(1.2*total*1000)+" mm (illustration only; thickness defines the property).";const scale=90/(total*1000);card.viewport?.setMetric?.({origin:{x:12,y:15},x:{x:scale,y:0},y:{x:0,y:scale},unit:"mm",gridSpacing:1});card.viewport?.refresh();}
  function update(key,notify=false){if(destroyed||updating)return;updating=true;try{refreshSelects();for(const card of cards)draw(card);try{const values=validate();for(const field of KEYS)canonical[field].value=JSON.stringify(values[field]);status.textContent="";status.hidden=true;for(const card of cards){card.error.hidden=true;card.error.textContent="";}}catch(error){status.textContent=error.message;status.hidden=false;for(const card of cards){card.error.textContent=error.message;card.error.hidden=!error.message.startsWith(card.label+":");}}add.disabled=library.length>=256;}finally{updating=false;}if(notify)onEdit(key);}
  function addLibrary(row){const wrap=el("article",undefined,"material-library-row"),top=el("div",undefined,"material-library-top"),id=el("strong","ID "+row.id),name=textInput(top,"Material "+row.id+" name",row.name),remove=el("button","Remove");remove.type="button";remove.title="Remove this material if no active component uses it";top.prepend(id);top.append(remove);const values=el("div",undefined,"material-library-values"),E=input(values,"E (GPa)",row.E,{scale:1e-9}),nu=input(values,"Poisson ratio",row.nu),rho=input(values,"Density (kg/m³)",row.rho);wrap.append(top,values);libraryBody.append(wrap);const record={id:row.id,wrap,name,E,nu,rho};library.push(record);for(const control of[name,E,nu,rho])listen(control,"input",()=>update(KEYS[0],true));listen(remove,"click",()=>{const uses=cards.filter(card=>{const value=rawCard(card);return(card.shell&&value.kind==="sandwich"?[value.face_material,value.core_material]:[value.material]).includes(record.id);});if(uses.length){status.hidden=false;status.textContent="Material "+record.id+" is used by "+uses.map(card=>card.label).join(", ")+". Assign another material before removing it.";return;}library.splice(library.indexOf(record),1);wrap.remove();update(KEYS[0],true);});return record;}
  for(const row of parsed[KEYS[0]])addLibrary(row);
  function addCard(def,shell){const[component,label,group,thicknessKey]=def,container=doc.getElementById(group)||host,table=shell?KEYS[1]:KEYS[2],initial=parsed[table].find(row=>row.component===component),row={material:1,kind:"monolithic",face_material:1,core_material:3,face_thickness:.0005,core_thickness:.01,...initial},section=el("section",undefined,"material-assignment"),heading=el("div",undefined,"materials-editor-heading"),help=el("button","ⓘ");help.type="button";help.setAttribute("aria-label","Help for "+label+" materials");heading.append(el("h4",label+" material"),help);section.append(heading);const hint=el("p",shell?"Monolithic uses the existing thickness field. Sandwich uses equal face layers around a core. Face thickness means each face; total = 2 × face + core. Per-rib and spar-bay thickness overrides change the total by adjusting only the core. Native sandwich z1/z2 results are first/last ply midpoint stresses, not outer-surface stresses or a failure criterion. "+SHARED_NOTE:"This isotropic material applies to the existing beam section dimensions. "+SHARED_NOTE,"material-note");hint.hidden=true;listen(help,"click",()=>{hint.hidden=!hint.hidden;});section.append(hint);const card={component,label,shell,section,present:!!initial,thicknessKey,error:el("p",undefined,"material-error")};card.error.setAttribute("role","status");card.error.hidden=true;
   if(shell){card.thicknessRow=doc.getElementById("p-"+thicknessKey)?.closest(".row");if(card.thicknessRow){card.thicknessWasHidden=card.thicknessRow.hidden;hidden.push([card.thicknessRow,card.thicknessWasHidden]);}card.kind=selection(section,label+" construction",[["monolithic","Monolithic"],["sandwich","Sandwich · face / core / face"]],row.kind);card.mono=el("div");section.append(card.mono);card.material=materialSelect(card.mono,label+" material",row.material);card.layers=el("div",undefined,"material-layer-fields");card.faceMaterial=materialSelect(card.layers,label+" face material",row.face_material);card.coreMaterial=materialSelect(card.layers,label+" core material",row.core_material);card.face=input(card.layers,label+" each face (mm)",row.face_thickness,{scale:1000});card.core=input(card.layers,label+" core (mm)",row.core_thickness,{scale:1000});section.append(card.layers);card.total=el("p",undefined,"material-total");card.preview=doc.createElementNS("http://www.w3.org/2000/svg","svg");card.preview.classList.add("material-cross-section");card.preview.setAttribute("viewBox","0 0 360 122");card.preview.setAttribute("role","img");card.preview.dataset.viewKey="material-"+component;const canvas=el("div",undefined,"material-preview-canvas");canvas.append(card.preview);card.sample=el("p",undefined,"material-note");section.append(card.total,canvas,card.sample);card.viewport=root.WingSVGViewport?.install(card.preview,{host:canvas,snapSelector:"rect",title:label+" material section",exportName:"material-"+component+".svg"});}else card.material=materialSelect(section,label+" material",row.material);
   section.append(card.error);container.append(section);nodes.push(section);cards.push(card);for(const control of section.querySelectorAll(".material-field input,.material-field select")){listen(control,control.tagName==="SELECT"?"change":"input",()=>{if(control.tagName==="SELECT"&&control!==card.kind)control.dataset.materialValue=control.value;card.present=true;update(table,true);});}
  }
  SHELLS.forEach(def=>addCard(def,true));BARS.forEach(def=>addCard(def,false));
  listen(add,"click",()=>{const used=new Set(library.map(row=>row.id));let id=2;while(used.has(id))id++;const row=addLibrary({id,name:"Material "+id,E:71e9,nu:.33,rho:2780});update(KEYS[0],true);row.name.focus();});
  const changed=event=>{const id=event.target.id||"";if(id.startsWith("p-material.")||id.startsWith("p-properties.")||id.startsWith("p-leading_edge.t_"))update();};listen(doc,"input",changed);listen(doc,"change",changed);update();
  return{readDrafts(){try{return validate();}catch{return raw();}},assertValidDraft(){const values=validate();for(const key of KEYS)canonical[key].value=JSON.stringify(values[key]);},refresh:()=>update(),destroy(){if(destroyed)return;destroyed=true;listeners.forEach(remove=>remove());cards.forEach(card=>card.viewport?.destroy());nodes.forEach(node=>node.remove());for(const[row,wasHidden]of hidden)row.hidden=wasHidden;}};
 }
 root.WingMaterialsEditor={install};
})(globalThis);
