/* Undeformed rib-plane datums. View helpers only: never FE or pick entities. */
(function (root, factory) {
  const api = factory();
  if (typeof module === "object" && module.exports) module.exports = api; else root.WingRibDatums = api;
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
  "use strict";
  const toView = point => [point[1], point[2], point[0]];
  const cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];
  function direction(raw,fallback) {
    if(raw===undefined)return fallback;
    if(!(Array.isArray(raw)||ArrayBuffer.isView(raw))||raw.length!==3||!Array.from(raw).every(Number.isFinite))return null;
    const length=Math.hypot(...raw);return length>1e-12 ? Array.from(raw,v=>v/length) : null;
  }
  function size(value = 1) {
    if (typeof value !== "number" || !Number.isFinite(value) || value <= 0) throw new Error("Rib datum side length must be a finite number greater than zero.");
    return value;
  }
  function layout(data, side = 1) {
    side = size(side); const ribs = data?.annotations?.ribs, squares = []; let skipped = 0;
    if (!Array.isArray(ribs)) return { side, count: 0, squares, skipped, note: "Rib datum metadata is unavailable. Recreate the FEM to display the undeformed rib planes." };
    const endEta = data?.model_params?.["box.end_eta"], half = side / 2;
    for (let i = 0; i < ribs.length; i++) {
      const rib = ribs[i], raw = rib?.datum_origin;
      if (!(Array.isArray(raw) || ArrayBuffer.isView(raw)) || raw.length !== 3 || !Array.from(raw).every(value => typeof value === "number" && Number.isFinite(value))) { skipped++; continue; }
      if (typeof rib.eta === "number" && (rib.eta < 0 || (typeof endEta === "number" && Number.isFinite(endEta) && rib.eta > endEta + 1e-12))) { skipped++; continue; }
      const origin = Array.from(raw), u=direction(rib.datum_u,[1,0,0]), proposedV=direction(rib.datum_v,[0,0,1]);
      if(!u||!proposedV){skipped++;continue;}
      const projection=u.reduce((sum,value,j)=>sum+value*proposedV[j],0);
      const v=direction(proposedV.map((value,j)=>value-projection*u[j]));
      if(!v){skipped++;continue;}
      const normal=cross(u,v);
      const corners=[[-1,-1],[1,-1],[1,1],[-1,1]].map(([a,b])=>origin.map((value,j)=>value+half*(a*u[j]+b*v[j])));
      // Keep unsupported coordinates away from float32 GPU buffers. Metadata
      // stays unchanged; an empty result reports that nothing can be drawn.
      if (!corners.flat().every(value => Number.isFinite(value) && Math.abs(value) <= 1e30)) { skipped++; continue; }
      squares.push({ index: Number.isInteger(rib.index) ? rib.index : i + 1, label: typeof rib.label === "string" ? rib.label : "Rib " + (i + 1),
        eta: rib.eta, origin, u, v, normal, corners, isMaster: rib.is_master === true || (rib.is_master === undefined && (i === 0 || i === ribs.length - 1)),
        color: (rib.is_master === true || (rib.is_master === undefined && (i === 0 || i === ribs.length - 1))) ? "#ff982f" : "#91c8ee" });
    }
    return { side, count: squares.length, squares, skipped,
      note: !squares.length ? "No usable rib datum origins are available. Recreate the FEM if it was generated by an older version." : skipped ? `${skipped} rib datum record(s) outside the box or without usable coordinates were omitted.` : "Undeformed rib datum planes, centred at the front spar and aligned with each rib." };
  }
  function create({ BABYLON: B = globalThis.BABYLON, scene }) {
    const meshes = {}; let current = layout(null), visible = false, disposed = false;
    const material = new B.StandardMaterial("rib-datums-material", scene);
    material.diffuseColor = B.Color3.Black(); material.emissiveColor = B.Color3.White(); material.specularColor = B.Color3.Black();
    material.disableLighting = true; material.backFaceCulling = false; material.twoSidedLighting = true;
    material.alpha = .18; material.transparencyMode = B.Material.MATERIAL_ALPHABLEND; material.disableDepthWrite = true; material.depthFunction = B.Constants.LEQUAL;
    function tag(mesh, kind) {
      mesh.isPickable = false; mesh.renderingGroupId = 0;
      mesh.metadata = { wingViewHelper: true, ribDatums: true, kind, frame: "Undeformed rib plane", side_m: current.side, count: current.count };
      mesh.setEnabled(visible && current.count > 0);
    }
    function update(data, side = 1) {
      if (disposed) throw new Error("Rib datum renderer has been disposed.");
      current = layout(data, side);
      if (!current.count) { for (const mesh of Object.values(meshes)) { tag(mesh, mesh.metadata?.kind || "planes"); mesh.setEnabled(false); } return current; }
      const positions = [], indices = [], normals = [], lines = [], colors = [], lineColors = [];
      for (const square of current.squares) {
        const offset = positions.length / 3, points = square.corners.map(toView);
        const rgb = B.Color3.FromHexString(square.color);
        for (const point of points) { positions.push(...point); normals.push(...toView(square.normal)); colors.push(rgb.r,rgb.g,rgb.b,1); }
        indices.push(offset, offset + 1, offset + 2, offset, offset + 2, offset + 3);
        lines.push(points.concat([points[0]]).map(point => B.Vector3.FromArray(point)));
        lineColors.push(points.concat([points[0]]).map(()=>new B.Color4(rgb.r,rgb.g,rgb.b,.55)));
      }
      const plane = meshes.planes || (meshes.planes = new B.Mesh("rib-datum-planes", scene)); plane.material = material;
      const vertexData = new B.VertexData(); vertexData.positions = positions; vertexData.indices = indices; vertexData.normals = normals; vertexData.colors = colors; vertexData.applyToMesh(plane, false);
      plane.refreshBoundingInfo(); plane.computeWorldMatrix(true); tag(plane, "planes");
      // One line system outlines every square; there is no mesh per rib.
      meshes.outline?.dispose();
      const outline = meshes.outline = B.MeshBuilder.CreateLineSystem("rib-datum-outlines", { lines, colors:lineColors, updatable: false }, scene);
      outline.color = B.Color3.White(); outline.alpha = 1;
      if (outline.material) { outline.material.disableDepthWrite = true; outline.material.depthFunction = B.Constants.LEQUAL; }
      tag(outline, "outline"); return current;
    }
    function setVisible(value) { visible = !!value; for (const mesh of Object.values(meshes)) mesh.setEnabled(visible && current.count > 0); }
    function dispose() { if (disposed) return; disposed = true; for (const [key, mesh] of Object.entries(meshes)) { mesh.dispose(); delete meshes[key]; } material.dispose(); }
    return { meshes, update, setVisible, dispose, get layout() { return current; } };
  }
  return { size, layout, toView, create };
});
