(function(){
 'use strict';const api=WingSensitivityTableData,effects=WingSensitivityResults,get=id=>document.getElementById(id),CHANNEL='WingFEGen.sensitivity-table.v1',token=location.hash.slice(1),parent=window.opener,origin=location.origin;
 let snapshot=api.compact(),connected=false,lastSeen=Date.now(),initialized=false;
 const send=type=>{if(parent&&!parent.closed)parent.postMessage({channel:CHANNEL,token,type},origin);};
 const format=value=>WingNumbers.format(value,7),node=(tag,text,cls)=>{const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(cls)el.className=cls;return el;};
 const options=()=>({mode:get('table-mode').value,skin:get('skin').value,field:get('field').value,quantity:get('quantity').value,filter:get('table-mode').value==='panels'?'':get('filter').value});
 function displayValue(row,parent){const data=api.value(snapshot.result,row,get('quantity').value),span=node('span',data.value===null?'Unavailable':format(data.value),'sensitivity-value '+(data.value===null?'value-unavailable':data.value<0?'value-negative':data.value>0?'value-positive':'value-zero'));span.title=data.value===null?data.reason:String(data.value)+' '+data.unit;span.dataset.value=data.value===null?'':String(data.value);parent.append(span);return data;}
 function fields(){const previous=get('field').value,items=api.families(snapshot.result);get('field').replaceChildren();for(const field of items){const option=node('option',field.name+(field.unit?' · '+field.unit:''));option.value=field.key;get('field').append(option);}if(items.some(f=>f.key===previous))get('field').value=previous;if(!initialized){get('table-mode').value=items.length?'panels':'all';initialized=true;}get('table-mode').querySelector('[value="panels"]').disabled=!items.length;if(!items.length&&get('table-mode').value==='panels')get('table-mode').value='all';}
 function render(){const result=snapshot.result,opts=options(),isGrid=opts.mode==='panels',head=get('sensitivity-table').tHead,body=get('sensitivity-table').tBodies[0];head.replaceChildren();body.replaceChildren();get('sensitivity-table').classList.toggle('sensitivity-list',!isGrid);get('skin-label').hidden=!isGrid;get('field-label').hidden=!isGrid;get('list-controls').querySelector('label').hidden=isGrid;
  const base=effects.baseline(result),compat=snapshot.compatibility||{},historical=result&&compat.is_current!==true,status=get('connection');status.classList.toggle('warning',!connected||!!historical);status.textContent=!connected?'Study window disconnected · displaying the last received result; CSV remains available.':historical?'Historical or unverified run · '+((compat.reasons||[]).join(' ')||'Review the recorded definition before comparing with the current Study.'):'Current sensitivity run · read-only data from the Study window.';get('table-error').hidden=!snapshot.error;get('table-error').textContent=snapshot.error;
  get('objective').textContent=result?(result.case_label||'Case '+(result.case_id||''))+' · '+effects.objectiveLabel(result):'No result';get('baseline').textContent=Number.isFinite(base.value)?'Baseline f = '+format(base.value)+' '+(base.unit||''):'Baseline unavailable';get('method').textContent=result?.method?'Method: '+result.method.replaceAll('_',' '):'';get('source-path').textContent=snapshot.sourcePath?'Source: '+snapshot.sourcePath:'';
  let count=0;if(isGrid&&result){const grid=api.matrix(snapshot,opts.skin,opts.field),header=head.insertRow();const first=node('th','Stringer ↓');first.scope='col';header.append(first);for(const bay of grid.bays){const th=node('th','R'+bay+'–R'+(bay+1));th.scope='col';header.append(th);}
   for(const stringer of grid.stringers){const tr=body.insertRow(),th=node('th',(opts.skin==='upper'?'U':'L')+stringer);th.scope='row';tr.append(th);for(const bay of grid.bays){const cell=tr.insertCell(),panels=grid.cells.get(stringer+':'+bay)||[];if(!panels.length){cell.className='no-panel';cell.textContent='—';continue;}for(const panel of panels){const wrap=node('div',undefined,'sensitivity-cell');wrap.dataset.panelKey=panel.key;wrap.append(node('strong',(panel.id?'P'+panel.id:'Panel ID unavailable')+(panels.length>1?' · segment '+panel.segment:'')));if(!panel.rows.length)wrap.append(node('span','Not analyzed','value-unavailable'));for(const row of panel.rows){count++;const value=displayValue(row,wrap);wrap.append(node('small',value.unit||row.derivative_unit||''));if(panel.rows.length>1)wrap.append(node('small',api.propertyLabel(row)));if(value.reason)wrap.append(node('small',value.reason,'value-note'));wrap.title=row.id+'\n'+(Number.isFinite(row.value)?'Property p = '+row.value+' '+(row.unit||''):'');}cell.append(wrap);}}}
  }else if(result){const header=head.insertRow();for(const label of ['Property','p','Property unit',opts.quantity==='normalized'?'p/f × df/dp':'df/dp','Derivative unit','Status / note']){const th=node('th',label);th.scope='col';header.append(th);}for(const row of api.selectRows(snapshot,opts)){count++;const tr=body.insertRow(),th=node('th',api.propertyLabel(row));th.scope='row';th.append(node('small',row.id));tr.append(th);tr.insertCell().textContent=format(row.value);tr.insertCell().textContent=row.unit||'';const value=displayValue(row,tr.insertCell());tr.insertCell().textContent=value.unit||row.derivative_unit||'';const status=tr.insertCell();status.textContent=value.status+(value.reason?' · '+value.reason:'');if(value.status!=='ok'||value.reason)status.className='row-warning';}}
  const total=result?.rows?.length||0;get('table-count').textContent=count+' displayed of '+total+' derivatives'+(isGrid?' · '+(opts.quantity==='normalized'?'dimensionless (p/f) × df/dp':'response units / property units'):'');get('csv').disabled=!count;get('empty').hidden=!!body.rows.length;get('empty').textContent=result?'No derivatives match this table or filter.':'Run sensitivity or open a saved run in the Study window.';get('sensitivity-table').hidden=!body.rows.length;
 }
 for(const id of ['table-mode','skin','field','quantity'])get(id).onchange=render;get('filter').oninput=render;get('help-button').onclick=()=>{get('help').hidden=!get('help').hidden;get('help-button').setAttribute('aria-expanded',String(!get('help').hidden));};
 get('csv').onclick=()=>{const text=api.csv(snapshot,options()),blob=new Blob([text],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=node('a');a.href=url;a.download='sensitivity-'+(snapshot.result?.case_id||'case')+'-'+options().mode+'-'+options().quantity+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 window.addEventListener('message',event=>{const data=event.data;if(event.origin!==origin||event.source!==parent||!data||data.channel!==CHANNEL||data.token!==token)return;lastSeen=Date.now();if(data.type==='snapshot'){snapshot=api.compact(data.snapshot);connected=true;fields();render();}else if(data.type==='disconnected'){connected=false;render();}});
 if(!parent||!token){get('connection').textContent='Open this table from Sensitivity in the WingFEGen Study window.';return;}send('ready');const timer=setInterval(()=>{if(parent.closed){connected=false;render();clearInterval(timer);}else{if(connected&&Date.now()-lastSeen>8000){connected=false;render();}send(connected?'ping':'ready');}},2000);window.addEventListener('pagehide',()=>clearInterval(timer),{once:true});
})();
