(function(root,factory){const api=factory();if(typeof module==="object"&&module.exports)module.exports=api;else root.WingSupports=api;})(globalThis,function(){
 "use strict";
 const TARGETS=[['front_spar','Front spar / rib line'],['rear_spar','Rear spar / rib line'],['upper_skin','Upper skin and stringers'],['lower_skin','Lower skin and stringers'],['front_upper','Front spar / upper skin corner'],['front_lower','Front spar / lower skin corner'],['rear_upper','Rear spar / upper skin corner'],['rear_lower','Rear spar / lower skin corner']];
 const DOFS=['Tx','Ty','Tz','Rx','Ry','Rz'];
 function canonical(rows){return rows.map(row=>({rib:row.rib,target:row.target,dofs:[...new Set(String(row.dofs))].sort().join('')}));}
 function install(host,{onEdit=()=>{},readRibs=()=>[],isLocked=()=>false}={}){
  const doc=host.ownerDocument,stored=doc.getElementById('p-supports.items'),mode=doc.getElementById('p-supports.mode');if(!stored||!mode)return null;
  doc.getElementById('row-supports.items').hidden=true;
  const el=(tag,cls,text)=>{const node=doc.createElement(tag);if(cls)node.className=cls;if(text!==undefined)node.textContent=text;return node;};
  const box=el('section','supports-editor'),intro=el('p','group-note','Choose a rib and the part to constrain. Select any combination of global DOFs: 1–3 translations x/y/z; 4–6 rotations about x/y/z. Spar lines include the nodes through the depth; skin rows include their stringer and spar-cap nodes. Corner selections constrain one shared node. Overlapping selections combine their DOFs.'),list=el('div','support-rows'),add=el('button','mini','+ Add support'),error=el('p','support-error'),note=el('p','pick-note');
  const glyphKey=el('p','pick-note','Support symbols: translations 1–3 are cones pointing along their positive global axis, with tips at the node; rotations 4–6 are open cubes offset half the Marker radius. Global x is red, y green, z blue. Change their size in Display.');
  box.id='support-definitions';add.type='button';add.id='support-add';error.setAttribute('role','alert');box.append(intro,glyphKey,list,add,error,note);host.append(box);const rows=[];
  function drafts(){return rows.map(row=>({rib:row.rib.value.trim()===''?null:Number(row.rib.value),target:row.target.value,dofs:row.buttons.filter(button=>button.checked).map(button=>button.value).join('')}));}
  function message(){const values=drafts(),ribs=readRibs()||[];for(let i=0;i<values.length;i++){const row=values[i];if(!Number.isInteger(row.rib)||row.rib<1)return 'Support '+(i+1)+': select a positive, whole rib number.';if(ribs.length&&row.rib>ribs.length)return 'Support '+(i+1)+': R '+row.rib+' is outside the current '+ribs.length+' ribs.';if(!row.dofs)return 'Support '+(i+1)+': select at least one DOF (1–6).';}return '';}
  function refresh(){const custom=mode.value==='custom',ribs=readRibs()||[];list.hidden=add.hidden=!custom;error.textContent=custom?message():'';error.hidden=!error.textContent;note.textContent=!custom?'Default: the main-box skin/spar perimeter of R 1 is constrained in DOFs 1, 2, 3. Leading-edge extension nodes are free.':rows.length?(ribs.length?ribs.length+' ribs in the current FEM. ':'')+'Support locations follow the numbered ribs when the layout changes.':'No constraints: add a support to restrain the model.';for(const row of rows){row.rib.disabled=row.target.disabled=row.remove.disabled=isLocked();row.buttons.forEach(button=>button.disabled=isLocked());}add.disabled=isLocked();}
  function sync(){stored.value=JSON.stringify(canonical(drafts()));refresh();onEdit('supports.items');}
  function append(value,notify=true){const card=el('fieldset','support-row'),legend=el('legend','','Support'),rib=el('input'),target=el('select'),remove=el('button','mini ghost','Remove');rib.type='number';rib.min='1';rib.step='1';rib.value=value.rib??1;rib.setAttribute('aria-label','Support rib');target.setAttribute('aria-label','Support location');for(const [key,label]of TARGETS){const option=el('option','',label);option.value=key;target.append(option);}target.value=value.target||'front_spar';const ribLabel=el('label','row','Rib'),targetLabel=el('label','row','Location');ribLabel.append(rib);targetLabel.append(target);const dofs=el('div','support-dofs');dofs.setAttribute('role','group');dofs.setAttribute('aria-label','Constrained degrees of freedom');const buttons=DOFS.map((name,index)=>{const label=el('label','support-dof'),button=el('input'),caption=el('span','',String(index+1));button.type='checkbox';button.value=String(index+1);button.checked=String(value.dofs??'3').includes(button.value);button.setAttribute('aria-label',button.value+' '+name);label.title=button.value+' = global '+name;label.append(button,caption);dofs.append(label);button.onchange=()=>{if(!isLocked())sync();};return button;});remove.type='button';remove.setAttribute('aria-label','Remove support');card.append(legend,ribLabel,targetLabel,dofs,remove);list.append(card);const row={rib,target,buttons,remove,card};rows.push(row);rib.oninput=target.onchange=()=>{if(!isLocked())sync();};remove.onclick=()=>{if(isLocked())return;rows.splice(rows.indexOf(row),1);card.remove();sync();};if(notify)sync();}
  let initial=[];try{initial=JSON.parse(stored.value||'[]');}catch(_){}for(const row of initial)append(row,false);
  add.onclick=()=>{if(!isLocked())append({rib:1,target:'front_spar',dofs:'3'});};const modeChanged=()=>refresh();mode.addEventListener('change',modeChanged);host.addEventListener('parameterlockchange',refresh);refresh();
  return{refresh,readDrafts:()=>({'supports.items':canonical(drafts())}),assertValidDraft(){if(mode.value==='custom'&&message())throw Error(message());},destroy(){mode.removeEventListener('change',modeChanged);host.removeEventListener('parameterlockchange',refresh);box.remove();}};
 }
 return{TARGETS,DOFS,canonical,install};
});
